/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClockMacDash.java
 *
 * Created on Nov 7, 2009, 10:40:39 PM
 */

package org.blackchip.widget.example.clock;

import org.blackchip.widget.TimeModel;
import org.blackchip.widget.WidgetPanel;

/**
 *
 * @author mcgann
 */
public class ClockMacDashFrame extends javax.swing.JFrame {

    private TimeModel model;
    private ClockMacDashPanel wp;

    /** Creates new form ClockMacDash */
    public ClockMacDashFrame(TimeModel model)
    {
        this.model = model;
        initComponents();
        wp = (ClockMacDashPanel)panel;
        model.addListener(wp);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        themeCombo = new javax.swing.JComboBox();
        panel = new ClockMacDashPanel(model);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        themeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "Night" }));
        themeCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                themeComboItemStateChanged(evt);
            }
        });
        themeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themeComboActionPerformed(evt);
            }
        });

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(themeCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 360, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(themeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themeComboActionPerformed

    }//GEN-LAST:event_themeComboActionPerformed

    private void themeComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_themeComboItemStateChanged
        String value = (String)themeCombo.getSelectedItem();
        if ( value.equals("Day") )
        {
            wp.day();
        }
        else if ( value.equals("Night") )
        {
            wp.night();
        }
    }//GEN-LAST:event_themeComboItemStateChanged



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox themeCombo;
    // End of variables declaration//GEN-END:variables

}
